### ISSUE TITLE
Sample app does not work in Xcode 8

### ISSUE THREAD

**Issue by AnthonyOliveri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security-googleauthentication#6]
When opening the sample GoogleMCA app in Xcode 8, the "Convert to Current Swift Syntax?" prompt appears, and the project fails to build.

**Comment by vitalymibm** [comment]
@AnthonyOliveri I converted the sample app to Swift 3, fixed compilation errors related to the new SDK signatures and added bridging header to settings. Now the project should compile fine (once you copy the google auth manager class to the project).
